### ISSUE TITLE
LocalGlyphRasterizer is not surviving R8 minify

### ISSUE THREAD

**Issue by spacetug** [mapbox/mapbox-gl-native-android#100]
Building android app with minify and R8 caused: 
```
 java.lang.NoSuchMethodError: no non-static method "Lcom/mapbox/mapboxsdk/text/LocalGlyphRasterizer;.<init>()V"
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeOnSurfaceCreated(Native Method)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onSurfaceCreated(MapRenderer.java:1)
        at L51.onSurfaceCreated(TextureViewMapRenderer.java:1)
        at T41.onSurfaceCreated(MapView.java:2)
        at N51.run(TextureViewRenderThread.java:41)
```

during runtime.

Solved by adding 
`-keep class com.mapbox.mapboxsdk.text.LocalGlyphRasterizer`

to pro-guard rules

**Comment by LukasPaczos** [comment]
Hey @spacetug, I'm unable to reproduce. Could you share the SDK version you're using and the build flags used for minification?

**Comment by LukasPaczos** [comment]
I was able to reproduce now, it doesn't always happen, looks like it happens only for fresh tiles or other variables.

**Comment by spacetug** [comment]
I'm sorry for the late response.
Yes, I forgot to mention, I need to zoom in in order to trigger the crash.
