### ISSUE TITLE
UnsatisfiedLinkError on debug mode change

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-gl-native-android#103]
```
Process: com.mapbox.mapboxsdk.testapp, PID: 27311
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.maps.NativeMapView.nativeCycleDebugOptions() (tried Java_com_mapbox_mapboxsdk_maps_NativeMapView_nativeCycleDebugOptions and Java_com_mapbox_mapboxsdk_maps_NativeMapView_nativeCycleDebugOptions__)
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeCycleDebugOptions(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.cycleDebugOptions(NativeMapView.java:591)
        at com.mapbox.mapboxsdk.maps.MapboxMap.cycleDebugOptions(MapboxMap.java:780)
        at com.mapbox.mapboxsdk.testapp.activity.maplayout.DebugModeActivity.lambda$setupDebugChangeView$4$DebugModeActivity(DebugModeActivity.java:168)
```

**Comment by tobrun** [comment]
This was removed upstream https://github.com/mapbox/mapbox-gl-native/pull/16005
