### ISSUE TITLE
mapbox crash on versions: [8.6.0 and 8.6.0-beta.1]

### ISSUE THREAD

**Issue by FaridBeiranvand** [mapbox/mapbox-gl-native-android#123]
Hi.im using mapbox in my project and i faced with crash in this versions:
8.6.0 and 8.6.0-beta.1
but this crash not occured in versions:
8.5.0,8.5.2,8.6.0-alpha.1
content of crash is:
` /usr/local/google/buildbot/src/android/ndk-release-r20/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating" failed

Fatal signal 6 (SIGABRT) at 0x000013a2 (code=-6), thread 5239 (Worker 1)

NativeCrashListener: Exception dealing with report
    libcore.io.ErrnoException: read failed: EAGAIN (Try again)
        at libcore.io.Posix.readBytes(Native Method)
        at libcore.io.Posix.read(Posix.java:128)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:149)
        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)`

after this app closed.please fix this.thanks

**Comment by hojatdelfan** [comment]
This problem has happened to me too

**Comment by another-dave** [comment]
Having this issue also, and can confirm that it seems to be happening on `8.6.0`, but not `8.5.2` or `8.6.0-alpha.1`.

Have also noticed 

* it only on Android 9/10, but not on a device running Android 7.
* cannot immediately reproduce with a [complete vanilla app](https://docs.mapbox.com/android/maps/examples/create-a-simple-map-view/) for `8.6.0`.

Trying to play spot the difference now between our Production app and the one activity toy that can't reproduce the problem. Will post a reproduce, verifiable example if possible.

**Comment by another-dave** [comment]
As a quick update, for me, this seems to be related to calling `LocationEngine.getLastLocation()` within the `Style.OnStyleLoaded` callback of the map set-up.

This is now failing on a screen where the user hasn't yet been prompted for Location permissions.

Not sure if anything changed there internally on the permissions required? Annoyingly, haven't yet been able to narrow it down further for a standalone verifiable example that passes on 8.5 but fails on 8.6.

**Comment by sys-samk** [comment]
Hello
This problem happened  to me 
My phone model is xiaomi 4x

Are you going to fix this issue?
Thanks.

**Comment by dragosrachieruroweb** [comment]
Same for me

**Comment by QuentinLB** [comment]
8.6.2 fixed the issue for me on a 5.1.1 tablet
