### ISSUE TITLE
Crash in SDK v8.6.1: java.lang.UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by maulikhirani** [mapbox/mapbox-gl-native-android#149]
I am using Mapbox in several screens of my app. The crash is observed only in production in some random devices.

Crash log:
`Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
       at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(NativeConnectivityListener.java)
       at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java)
       at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java)
       at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java)
       at com.way.app.application.WayApplication.onCreate(WayApplication.java)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4577)
       at android.app.ActivityThread.access$1500(ActivityThread.java:156)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5278)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:373)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

We're initializing Mapbox SDK in Application class, and that's where the crash is occuring.

**SDK Version:**
8.6.1
**Devices facing crash:**
Vivo S1, Samsung Galaxy A70, Xiaomi Mi 9X, LGE Nexus 5
**OS Versions**
Android 5 (79%), Android 6, Android 7

Seems this is happening only when app is published using Android App Bundle format.

**Comment by tobrun** [comment]
Following up on this in #416
