### ISSUE TITLE
[Android] java.lang.UnsatisfiedLinkError when initializing SDK 

### ISSUE THREAD

**Issue by schachi5000** [mapbox/mapbox-gl-native-android#208]
Currently we experiencing following error when trying to initialize the Android SDK with our token.

`java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
	at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
	at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
	at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:64)`

SDK Version: 8.3.0
Android API Level: 28
Device Huawei MediaPad M5 (JDN2-L09 )

**Comment by tobrun** [comment]
Following up on this in #416
