### ISSUE TITLE
Test case locationComponentOptions_customGpsIconNameChangeBackWithMode not stable.

### ISSUE THREAD

**Issue by Chaoba** [mapbox/mapbox-gl-native-android#332]
Test LocationComponentOptions_customGpsIconNameChangeBackWithMode would fail occasionally with the following stack.
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at java.util.Arrays$ArrayList.get(Arrays.java:3769)
at com.mapbox.mapboxsdk.location.LocationComponentTest$locationComponentOptions_customGpsIconNameChangeBackWithMode$componentAction$1.onLocationComponentAction(LocationComponentTest.kt:440)
at com.mapbox.mapboxsdk.location.utils.LocationComponentAction.perform(LocationComponentAction.kt:27)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:366)
at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:255)
at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:65)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:158)
at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:155)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6541)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Chaoba** [comment]
By the test [video](https://console.firebase.google.com/u/0/project/mapbox-gl-native-android/testlab/histories/bh.c6767b491a06da0a/matrices/5824598288235097946/executions/bs.dbe0e214ef272d97/testcases/24/video), it seems location force update not works.

**Comment by Chaoba** [comment]
Can reproduce this issue locally by running the test case for dozens of times. 

Dump the sources in the following way
![image](https://user-images.githubusercontent.com/8577318/80599393-6fc51500-8a5d-11ea-9005-6d580d9374a3.png)

When test case fails, will get the following log. From the log, `mapbox-location-source` is not renderable and not complete, while for a success case, both of them are yes. 
```
2020-04-29 21:01:49.078 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: mapbox-location-source
2020-04-29 21:01:49.079 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.080 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/0/0=>1
2020-04-29 21:01:49.080 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: no
2020-04-29 21:01:49.080 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: no
2020-04-29 21:01:49.081 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.081 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/0/1=>1
2020-04-29 21:01:49.081 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: no
2020-04-29 21:01:49.082 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: no
2020-04-29 21:01:49.082 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.083 12739-12739/com.mapbox.mapboxsdk.testapp E/ANR_LOG: >>> msg's executing time is too long
2020-04-29 21:01:49.083 12739-12739/com.mapbox.mapboxsdk.testapp E/ANR_LOG: Blocked msg = { when=-15s218ms what=0 target=android.os.Handler callback=androidx.test.espresso.core.internal.deps.guava.util.concurrent.ListenableFutureTask } , cost  = 15218 ms
2020-04-29 21:01:49.083 12739-12739/com.mapbox.mapboxsdk.testapp E/ANR_LOG: >>>Current msg List is:
2020-04-29 21:01:49.083 12739-12739/com.mapbox.mapboxsdk.testapp E/ANR_LOG: Current msg <1>  = { when=+14s934ms what=1 target=com.mapbox.mapboxsdk.location.StaleStateManager$StaleMessageHandler }
2020-04-29 21:01:49.083 12739-12739/com.mapbox.mapboxsdk.testapp E/ANR_LOG: >>>CURRENT MSG DUMP OVER<<<
2020-04-29 21:01:49.083 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/1/0=>1
2020-04-29 21:01:49.084 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: no
2020-04-29 21:01:49.084 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: no
2020-04-29 21:01:49.084 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.084 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/1/1=>1
2020-04-29 21:01:49.085 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: no
2020-04-29 21:01:49.085 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: no
2020-04-29 21:01:49.085 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: com.mapbox.annotations
2020-04-29 21:01:49.085 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.085 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/0/0=>1
2020-04-29 21:01:49.086 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.086 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.086 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.087 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/0/1=>1
2020-04-29 21:01:49.089 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.089 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.089 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.090 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/1/0=>1
2020-04-29 21:01:49.090 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.090 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.090 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.090 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/1/1=>1
2020-04-29 21:01:49.090 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.091 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.091 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: composite
2020-04-29 21:01:49.091 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.091 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 0/0/0=>0
2020-04-29 21:01:49.091 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.092 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.092 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.092 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/0/0=>1
2020-04-29 21:01:49.092 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.092 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.092 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.093 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/0/1=>1
2020-04-29 21:01:49.093 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.093 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.093 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.093 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/1/0=>1
2020-04-29 21:01:49.093 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.094 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.094 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::Kind: Geometry
2020-04-29 21:01:49.094 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::id: 1/1/1=>1
2020-04-29 21:01:49.094 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::renderable: yes
2020-04-29 21:01:49.094 12739-12800/com.mapbox.mapboxsdk.testapp I/Mbgl: {GLThread 2312}[General]: Tile::complete: yes
2020-04-29 21:01:49.094 12739-12800/com.mapbox.mapboxsdk.testapp E/Mbgl: {pboxsdk.testapp}[JNI]: test==  querySourceFeatures 0

```

**Comment by Chaoba** [comment]
@alexshalamov Any idea what would cause `mapbox-location-source` not rendered?

**Comment by Chaoba** [comment]
By adding some logs found that the reason `mapbox-location-source` is not rendered is that this source is not layout yet because of miss the image `custom-gps-bitmap`.  If a source is not layout, it's renderable property will be false.

While most of the time, the test case could pass is because for some reason, image `mapbox-location-stroke-icon` could trigger `mapbox-location-source` to layout like the following logs demostrated. 

```
-14 14:53:05.148 22388 22449 E Mbgl    : {GLThread 1204}[JNI]: Renderer::render
05-14 14:53:05.148 22388 22449 E Mbgl    : {GLThread 1204}[JNI]: ImageManager:: notifyIfMissingImageAdded
05-14 14:53:05.148 22388 22449 I Mbgl    : {GLThread 1204}[General]: ImageManager::onImagesAvailable：mapbox-location-stroke-icon
05-14 14:53:05.148 22388 22449 I Mbgl    : {GLThread 1204}[General]: ImageManager::notify::onImagesAvailable：
05-14 14:53:05.152 22388 22449 E Mbgl    : {Worker 1}[JNI]: GeometryTileWorker::onImagesAvailable:mapbox-location-source  mapbox-location-stroke-icon
05-14 14:53:05.152 22388 22449 E Mbgl    : {Worker 1}[JNI]: GeometryTileWorker::symbolDependenciesChanged
05-14 14:53:05.152 22388 22449 E Mbgl    : {Worker 1}[JNI]: GeometryTileWorker::finalizeLayoutmapbox-location-source
05-14 14:53:05.152 22388 22449 E Mbgl    : {Worker 1}[JNI]: GeometryTileWorker::invoke onLayout
```
