### ISSUE TITLE
[Android] IllegalArgumentException with EGLConfigChooser

### ISSUE THREAD

**Issue by Mordag** [mapbox/mapbox-gl-native-android#374]
I have observed some crashes with mapbox related to the EGLConfigChooser. I can't really name details, but I have noticed crashes since updating to mapbox 7.x with devices running Android 7.x.

```
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr(EGLConfigChooser.java:276)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig(EGLConfigChooser.java:201)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:84)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1051)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1421)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)
```

And another:

```
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr(EGLConfigChooser.java:274)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig(EGLConfigChooser.java:199)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:84)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1051)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1421)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)
```

Is it possible if someone takes a look at this crash? Maybe it is caused by some recent changes?

If there are no changes made that should case this issue, is it possible to translate this exception into something which only creates a log? Or is that going to create even more issues?

### Configuration

**Android versions:** 7.1.1, 7.0.0
**Device models:** Galaxy Tab A 8.0
**Mapbox SDK versions:** 7.2.0

**Comment by moritzzzzz** [comment]
Also happening for me:

```
Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl.eglGetConfigAttrib(EGLImpl.java)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.getConfigAttr(EGLConfigChooser.java:276)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseBestMatchConfig(EGLConfigChooser.java:201)
       at com.mapbox.mapboxsdk.maps.renderer.egl.EGLConfigChooser.chooseConfig(EGLConfigChooser.java:84)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1051)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1421)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1268)
```

Dependencies:
```
"com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0",
"com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0",
"com.mapbox.mapboxsdk:mapbox-sdk-turf:5.1.0",
"com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0",
"com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6"
```

**Comment by Chaoba** [comment]
Based on this [source code ](https://android.googlesource.com/platform/frameworks/base/+/master/core/jni/com_google_android_gles_jni_EGLImpl.cpp#318) in the following conditions, it will throw an exception
```
if (display == NULL || config == NULL
   || (value == NULL || _env->GetArrayLength(value) < 1)) {
   jniThrowException(_env, "java/lang/IllegalArgumentException", NULL);
   return JNI_FALSE;
 }
```
If `display` is null, the previous call `eglChooseConfig` method will throw exception, so display will not be null.
`value` is created by `int[] attributevalue = new int[1];`, so it will not be null or empty.

So, the only one could cause this exception would `config == NULL`
