### ISSUE TITLE
Directly including SDK in Android app isn't working

### ISSUE THREAD

**Issue by dmytroKarataiev** [mapbox/mapbox-gl-native-android#618]
When following this approach from here: https://docs.mapbox.com/android/maps/overview/#add-the-dependency:

```
You can also download the Maps SDK for Android directly. You need to be signed in to your Mapbox account to download the SDK directly.

Download the SDK with the link below.

Unzip the file and import the aar into your project using the Android Studio import function. Click on the File menu, then select New, New Module, and click on Import .JAR/.AAR package.

Include the project in your application's build.gradle file:

dependencies {
  ...
  implementation project(':mapbox-android-sdk-9.5.0')
  ...
}
```

The app also needs the following dependency included separately:
```
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.7.0'
``` 

And then app crashes with the following stacktrace:

```
2020-11-09 14:37:37.646 28626-28626/com.fundrise.android.debugStaging E/id.debugStagin: No implementation found for void com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeInitialize(com.mapbox.mapboxsdk.maps.renderer.MapRenderer, float, java.lang.String) (tried Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize and Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize__Lcom_mapbox_mapboxsdk_maps_renderer_MapRenderer_2FLjava_lang_String_2)
2020-11-09 14:37:37.647 28626-28626/com.fundrise.android.debugStaging D/AndroidRuntime: Shutting down VM
2020-11-09 14:37:37.648 28626-28626/com.fundrise.android.debugStaging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fundrise.android.debugStaging, PID: 28626
    android.view.InflateException: Binary XML file line #66 in com.fundrise.android.debugStaging:layout/fragment_project_map: Binary XML file line #66 in com.fundrise.android.debugStaging:layout/fragment_project_map: Error inflating class com.mapbox.mapboxsdk.maps.MapView
    Caused by: android.view.InflateException: Binary XML file line #66 in com.fundrise.android.debugStaging:layout/fragment_project_map: Error inflating class com.mapbox.mapboxsdk.maps.MapView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at e.f.a.g0.q3.d(FragmentProjectMapBinding.java:89)
        at e.f.a.j0.u.g.a.onCreateView(ProjectMapFragment.kt:79)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at c.o.d.q.e(FragmentStateManager.java:320)
        at c.o.d.l.D0(FragmentManager.java:1199)
        at c.o.d.l.C0(FragmentManager.java:1368)
        at c.o.d.l.A0(FragmentManager.java:1446)
        at c.o.d.a.F(BackStackRecord.java:442)
        at c.o.d.l.S(FragmentManager.java:2181)
        at c.o.d.l.T(FragmentManager.java:2004)
        at c.o.d.l.R0(FragmentManager.java:1959)
        at c.o.d.l.R(FragmentManager.java:1830)
        at c.o.d.a.l(BackStackRecord.java:297)
        at androidx.viewpager2.adapter.FragmentStateAdapter.r(FragmentStateAdapter.java:341)
        at androidx.viewpager2.adapter.FragmentStateAdapter.o(FragmentStateAdapter.java:276)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
        at androidx.recyclerview.widget.RecyclerView.z(RecyclerView.java:7556)
        at androidx.recyclerview.widget.RecyclerView$e.a(RecyclerView.java:860)
        at c.y.d.f.a(ChildHelper.java:107)
        at androidx.recyclerview.widget.RecyclerView$o.p(RecyclerView.java:8601)
        at androidx.recyclerview.widget.RecyclerView$o.o(RecyclerView.java:8559)
        at androidx.recyclerview.widget.RecyclerView$o.n(RecyclerView.java:8547)
        at androidx.recyclerview.widget.LinearLayoutManager.A2(LinearLayoutManager.java:1641)
        at androidx.recyclerview.widget.LinearLayoutManager.d2(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.J2(LinearLayoutManager.java:1391)
        at androidx.recyclerview.widget.LinearLayoutManager.E1(LinearLayoutManager.java:1116)
        at androidx.recyclerview.widget.RecyclerView.i1(RecyclerView.java:1838)
        at androidx.recyclerview.widget.RecyclerView$z.j(RecyclerView.java:11920)
        at androidx.recyclerview.widget.RecyclerView$c0.run(RecyclerView.java:5390)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
        at android.view.Choreographer.doCallbacks(Choreographer.java:797)
        at android.view.Choreographer.doFrame(Choreographer.java:728)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8154)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2020-11-09 14:37:37.648 28626-28626/com.fundrise.android.debugStaging E/AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeInitialize(com.mapbox.mapboxsdk.maps.renderer.MapRenderer, float, java.lang.String) (tried Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize and Java_com_mapbox_mapboxsdk_maps_renderer_MapRenderer_nativeInitialize__Lcom_mapbox_mapboxsdk_maps_renderer_MapRenderer_2FLjava_lang_String_2)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeInitialize(Native Method)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.<init>(MapRenderer.java:40)
        at e.i.b.u.e0.b.a.<init>(GLSurfaceViewMapRenderer.java:32)
        at com.mapbox.mapboxsdk.maps.MapView$e.<init>(MapView.java:331)
        at com.mapbox.mapboxsdk.maps.MapView.u(MapView.java:331)
        at com.mapbox.mapboxsdk.maps.MapView.x(MapView.java:145)
        at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:110)
        	... 49 more
```

**Comment by tobrun** [comment]
Thank you for the report, with transitive dependencies it's not working as expected and have remove the direct download option from our webpage.
