### ISSUE TITLE
StrictMode violation - Tried to access visual service WindowManager from a non-visual Context

### ISSUE THREAD

**Issue by eygraber** [mapbox/mapbox-gl-native-android#660]
```
2021-03-19 15:26:21.569 E/ContextImpl: Tried to access visual service WindowManager from a non-visual Context:com.app.MyApp@e498620 Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
    java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.app.MyApp@e498620
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1914)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:803)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.obtainDisplayDensity(PhoneState.java:61)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:43)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:305)
        at com.mapbox.mapboxsdk.maps.SupportMapFragment.onViewCreated(SupportMapFragment.java:112)
```

**Comment by Bradeskojest** [comment]
I noticed the same issue

**Comment by kotlincodes** [comment]
Any update on this isssue
