### ISSUE TITLE
NotFoundException when inflating MapView

### ISSUE THREAD

**Issue by Jukurrpa** [mapbox/mapbox-gl-native-android#92]
We've had a user encounter the same crash multiple times when the `MapView` was being inflated: `android.content.res.Resources$NotFoundException: Resource ID #0x7f070107`

SDK Version: 8.5.1
Android version: 9 (Samsung Galaxy S8)

Not sure how I can help as I can't reproduce the issue. Let me know if you need any other information.

Here is the MapView definition in the layout:
```
    <com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#CCCCCC"
        app:mapbox_uiCompass="false"
        app:mapbox_uiRotateGestures="true"
        app:mapbox_uiTiltGestures="false" />
```

And here is the full track trace:
```
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f070107
       at android.content.res.ResourcesImpl.getValueForDensity + 237(ResourcesImpl.java:237)
       at android.content.res.Resources.getDrawableForDensity + 902(Resources.java:902)
       at android.content.res.Resources.getDrawable + 842(Resources.java:842)
       at androidx.core.content.res.ResourcesCompat.getDrawable + 83(ResourcesCompat.java:83)
       at com.mapbox.mapboxsdk.maps.MapboxMapOptions.createFromAttributes + 225(MapboxMapOptions.java:225)
       at com.mapbox.mapboxsdk.maps.MapboxMapOptions.createFromAttributes + 170(MapboxMapOptions.java:170)
       at com.mapbox.mapboxsdk.maps.MapView.<init> + 100(MapView.java:100)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance + 343(Constructor.java:343)
       at android.view.LayoutInflater.createView + 647(LayoutInflater.java:647)
       at android.view.LayoutInflater.createViewFromTag + 790(LayoutInflater.java:790)
       at android.view.LayoutInflater.createViewFromTag + 730(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate + 863(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate + 515(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate + 423(LayoutInflater.java:423)
       at com.myapp.MapFragment.onCreateView + 191(MapFragment.java:191)
       at androidx.fragment.app.Fragment.performCreateView + 2600(Fragment.java:2600)
       at androidx.fragment.app.FragmentManagerImpl.ensureInflatedFragmentView + 1138(FragmentManagerImpl.java:1138)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 851(FragmentManagerImpl.java:851)
       at androidx.fragment.app.FragmentManagerImpl.moveToState + 1133(FragmentManagerImpl.java:1133)
       at androidx.fragment.app.FragmentManagerImpl.addFragment + 1393(FragmentManagerImpl.java:1393)
       at androidx.fragment.app.FragmentManagerImpl.onCreateView + 3205(FragmentManagerImpl.java:3205)
       at androidx.fragment.app.FragmentController.onCreateView + 134(FragmentController.java:134)
       at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView + 357(FragmentActivity.java:357)
       at androidx.fragment.app.FragmentActivity.onCreateView + 336(FragmentActivity.java:336)
       at android.view.LayoutInflater.createViewFromTag + 780(LayoutInflater.java:780)
       at android.view.LayoutInflater.createViewFromTag + 730(LayoutInflater.java:730)
       at android.view.LayoutInflater.rInflate + 863(LayoutInflater.java:863)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.rInflate + 866(LayoutInflater.java:866)
       at android.view.LayoutInflater.rInflateChildren + 824(LayoutInflater.java:824)
       at android.view.LayoutInflater.inflate + 515(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate + 423(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate + 374(LayoutInflater.java:374)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView + 555(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView + 161(AppCompatActivity.java:161)
       at com.myapp.MainActivity.onCreate + 62(MainActivity.java:62)
       at android.app.Activity.performCreate + 7327(Activity.java:7327)
       at android.app.Activity.performCreate + 7318(Activity.java:7318)
       at android.app.Instrumentation.callActivityOnCreate + 1271(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity + 3094(ActivityThread.java:3094)
       at android.app.ActivityThread.handleLaunchActivity + 3257(ActivityThread.java:3257)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1948(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7050(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 965(ZygoteInit.java:965)
```

**Comment by prengifo** [comment]
Hi!

Are there any developments on this issue? We are having the same problem with SDK 9.1.2 on Huawei devices. Android versions 9 & 10.

```
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x7f0701bb
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:340)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:993)
       at android.content.res.Resources.getDrawable(Resources.java:933)
       at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:83)
       at com.mapbox.mapboxsdk.maps.MapboxMapOptions.createFromAttributes(MapboxMapOptions.java:239)
       at com.mapbox.mapboxsdk.maps.MapboxMapOptions.createFromAttributes(MapboxMapOptions.java:178)
       at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:108)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at android.view.LayoutInflater.createView(LayoutInflater.java:864)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:1133)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
```
